# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: './' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: './README.md'

html_url_prefix: '/kingdom-of-vallonde'
site_name: 'Kingdom of Vallonde'

included_file_suffixes: ['jpg', 'jpeg', 'gif', 'png', 'svg', 'bmp', 'pdf', 'mp4', 'webm', 'mp3', 'wav']

# Provide an array of custom inclusions (css, javascript, etc) that you would like to be included in the resultant html
#html_custom_inclusions:
#- '<link rel="shortcut icon" href="/artyrix-campaign/img/.resources/dice-d20-solid.svg" sizes="any" type="image/svg+xml">'

toggles:
  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: True

exclude_subfolders:
  - ".obsidian"
  - "output"
  - "dm"
  - "dm/sessions"
  - ".DS_Store"
  - ".git"
  - "venv"
